### PR TITLE
ici cohort selection now has no module availitbility

### PR DESCRIPTION
**Pull request by andrewelamb**

### CODE REVIEW

**Comment by andrewelamb** [comment]
fixes #180

**Comment by heimannch** [comment]
I suggest to also remove the sentence "Specific analysis modules (displayed after you make your selection) are available for each dataset." from the text box above the selection of datasets.

**Comment by andrewelamb** [comment]
@heimannch Could you take a look again, after the latest commits?

**Comment by heimannch** [comment]
Looks good!

**Pull request merged**
