### PR TITLE
Update r2

### LINKED ISSUE #220: Update R,BioC, packages
R needs to be updated to 4.2 and Bioconductor need to be updated to 3.15.

### PR DESCRIPTION
**Pull request by andrewelamb**
fixes #220

### CODE REVIEW

**Comment by andrewelamb** [comment]
@heimannch Several Bioconductor packages were removed to get this working. Please add them back to the renv.lock file as needed.

**Comment by andrewelamb** [comment]
See #221

**Comment by andrewelamb** [comment]
@heimannch Is this working now?

**Comment by heimannch** [comment]
Yes, it's the current version in the testing app!

**Pull request merged**
